"2330": { name: 台積電, industry: 半導體 }
"2317": { name: 鴻海,   industry: 電子 }
"2454": { name: 聯發科, industry: 半導體 }
"2382": { name: 廣達,   industry: 電腦及週邊設備 }
"2303": { name: 聯電,   industry: 半導體 }
"2308": { name: 台達電, industry: 電子零組件 }
"2881": { name: 富邦金, industry: 金融保險 }
"2882": { name: 國泰金, industry: 金融保險 }
